import { MovieCard } from "@/components/movie/MovieCard";
import Head from "next/head";
import { useEffect, useState } from "react";
import { IMovie } from "../interface/movie";

export async function getStaticProps() {
  const response = await fetch(`http://localhost:7070/api/movies?limit=12`);
  const data = await response.json();
  return {
    props: { movies: data },
  };
}

export default function Home({
  movies: data,
}: {
  movies: IMovie[];
}): JSX.Element {
  const [movies, setMovies] = useState<IMovie[]>(data);
  const [ordering, setOrdering] = useState<string>("");

  useEffect(() => {
    fetch(`http://localhost:7070/api/movies?limit=12&ordering=${ordering}`)
      .then((res) => res.json())
      .then((data) => {
        setMovies(data);
      });
  }, [ordering]);

  return (
    <>
      <Head>
        <title>My client project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 min-h-screen">
        <div className="container mx-auto">
          <div className="bg-white">
            <select
              value={ordering}
              onChange={(e): void => {
                setOrdering(e.target.value);
              }}
              name="bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500"
              id=""
            >
              <option value="releasedAsc">Oldest</option>
              <option value="releasedDesc">Newest</option>
              <option value="imdbRatingDesc">Most Popular</option>
              <option value="titleAsc">A-Z</option>
              <option value="titleDesc">Z-A</option>
            </select>
            <input className="ml-5" type="text" placeholder="search" />
            <div className="p-4 grid grid-cols-6 gap-4">
              {movies.map((movie) => (
                <MovieCard movie={movie} key={movie._id} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
