import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

interface MovieAwards {
  wins: number;
  nominations: number;
  text: string;
}

interface MovieIMD {
  rating: number;
  votes: number;
  id: number;
}

interface MovieTomatoes {
  viewer: {
    rating: number;
    numReviews: number;
    meter: number;
  };
  lastUpdated: Date;
}

export interface IMovie {
  _id: string;
  poster?: string;
  plot: string;
  genres: string[];
  runtime: number;
  cast: string[];
  num_mflix_comments: number;
  title: string;
  fullplot: string;
  countries: string[];
  released: Date;
  directors: string[];
  rated: string;
  awards: MovieAwards;
  lastupdated: Date;
  year: number;
  imdb: MovieIMD;
  type: string;
  tomatoes: MovieTomatoes;
}

export default function Home(): JSX.Element {
  const [movies, setMovies] = useState<IMovie[]>([]);
  const placeHolder = "https://via.placeholder.com/160x230";

  useEffect(() => {
    fetch("http://localhost:7070/api/movies?limit=12")
      .then((res) => res.json())
      .then((data) => {
        setMovies(data);
      });
  }, []);

  return (
    <>
      <Head>
        <title>My client project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 min-h-screen">
        <div className="container mx-auto">
          <div className="bg-white">
            <div className="p-4 grid grid-cols-6 gap-4">
              {movies.map((movie) => (
                <div key={movie._id} className="group">
                  <div className="aspect-[16/23] relative group">
                    <Image
                      src={movie.poster || placeHolder}
                      alt={movie.title}
                      width={160}
                      height={230}
                      className="w-full h-full object-cover rounded"
                    />
                    <div className="absolute inset-0 group-hover:bg-black/30 transition-all" />
                  </div>
                  <Link
                    href={""}
                    className="text-xs text-stone-800	group-hover:text-sky-300 transition-colors"
                  >
                    {movie.title}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
